version: "3.7"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
